local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("MobSpells", "deDE")
if not L then return end

L["Show MobSpells"] = "Zeige MobSpells"
L["Report target's spells"] = "Berichte Zauber des Ziels"
L["Report your target spells to the group"] = "Teilt die Zauber des Ziels deiner Gruppe mit"
L["Now showing abilities in tooltip"] = "Zeige jetzt die Fähigkeiten im Tooltip an"
L["NOT showing abilities in tooltip"] = "Zeige jetzt keine Fähigkeiten im Tooltip an"
L["Use Tooltips"] = "Benutze Tooltips"
L["Show spell info in tooltips"] = "Zeigt Zauberinformation im Tooltip an"
L["Casts"] = "Wirkt"
L["Spell ID"] = true
L["Melee Attack"] = "Nahkampf Angriff"
L["School"] = "Schule"
L["Every"] = "Alle"
L["seconds"] = "sekunden"
L["Can miss"] = "Kann verfehlen"
L["Can fully resist"] = "Komplett widerstehbar"
L["Can be reflected"] = "Reflektierbar"
L["Can be dodged"] = "Ausweichbar"
L["Can be parried"] = "Parrierbar"
L["Can be resisted"] = "Widerstehbar"
L["Can be blocked"] = "Blockbar"
L["Can be dispelled"] = "Dispell-bar"
L["Can be stolen"] = "Klaubar (Magier)"
L["Can be interrupted"] = "Unterbrechbar"
L["Can crit"] = "Kann \'critten\'"
L["Can crush"] = "Kann \'crushen'"
L["Can glance"] = true
L["No target selected"] = "Kein Ziel ausgewählt"
L["Heroic"] = "Heroisch"
L["Config"] = "Konfiguration"
L["Configure MobSpells"] = "Konfiguriere MobSpells"