local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("MobSpells", "enUS", true)
if not L then return end

L["Show MobSpells"] = true
L["Report target's spells"] = true
L["Report your target spells to the group"] = true
L["Now showing abilities in tooltip"] = true
L["NOT showing abilities in tooltip"] = true
L["Use Tooltips"] = true
L["Show spell info in tooltips"] = true
L["Casts"] = true
L["Spell ID"] = true
L["Melee Attack"] = true
L["School"] = true
L["Every"] = true
L["seconds"] = true
L["Can miss"] = true
L["Can fully resist"] = true
L["Can be reflected"] = true
L["Can be dodged"] = true
L["Can be parried"] = true
L["Can be resisted"] = true
L["Can be blocked"] = true
L["Can be dispelled"] = true
L["Can be stolen"] = true
L["Can be interrupted"] = true
L["Can crit"] = true
L["Can crush"] = true
L["Can glance"] = true
L["No target selected"] = true
L["Heroic"] = true
L["Config"] = true
L["Configure MobSpells"] = true
L["Record in ..."] = true
L["Outside"] = true
L["Whether to record when you're not in a battleground, arena or PvE instance."] = true
L["PvP battleground"] = true
L["Whether to record when you're in a battleground."] = true
L["Arena"] = true
L["Whether to record when you're in an arena battle."] = true
L["5-man instance"] = true
L["Whether to record when you're in a 5-man instance."] = true
L["Raid instance"] = true
L["Whether to record when you're in a raid instance."] = true
L["Record when ..."] = true
L["Solo"] = true
L["Whether to record when you're playing solo."] = true
L["Party"] = true
L["Whether to record when you're in a 5-man group."] = true
L["Raid"] = true
L["Whether to record when you're in a raid group."] = true
L["Only record in Heroic difficulty"] = true
L["Toggle whether to record ONLY in Heroic difficulty settings."] = true
L["description"] = "MobSpells records spells cast by unfriendly NPCs and groups them by zone and difficulty, allowing you to do a in-game lookup of mob abilities. Click the button below to bring up the list of recorded spells.\n\nNote that the database can grow quite large after some time, so it might be a good idea to use the toggle options below to record only the data you are interested in."
L["Mob Spells"] = true
L["NPCs"] = true
L["Search"] = true
L["Spells"] = true
L["Deleted "] = true
L["Delete this spell"] = true
L["Cancel"] = true
L["Delete this mob"] = true
L["Delete this zone"] = true
L[" casts: "] = true
L["No recorded spells for "] = true
L["Keywords"] = true
L["Difficulty ..."] = true
L["Record in %s."] = true
L["Record in %s (%s)."] = true
L["Find Target"] = true
L["Report this mob"] = true
L["Unnamed Mob found adding it as 'Unknown'"] = true
L["Zones"] = true
L["Event"] = true
L["Event Scenario"] = true
L["5 man (Mythic)"] = true
L["Timewalker"] = true
